# Generated by Django 3.2.14 on 2022-07-18 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$')], verbose_name='username')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('nickname', models.CharField(max_length=10, verbose_name='表示名')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='プロフィール画像')),
                ('url', models.URLField(blank=True, null=True, verbose_name='リンク')),
                ('introduction', models.TextField(blank=True, max_length=300, null=True, verbose_name='自己紹介')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
