# Generated by Django 3.2.14 on 2022-07-20 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth of day'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='introduction',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=10, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$')], verbose_name='Username'),
        ),
    ]
