# Generated by Django 3.2.14 on 2022-07-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butter', '0004_instapost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instapost',
            new_name='Post',
        ),
    ]
